import { jsPDF } from 'jspdf';

export function exportCanvasToPNG(canvas: HTMLCanvasElement, filename = 'floor-plan') {
  const link = document.createElement('a');
  link.download = `${filename}.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
}

export function exportCanvasToJPG(canvas: HTMLCanvasElement, filename = 'floor-plan') {
  const link = document.createElement('a');
  link.download = `${filename}.jpg`;
  link.href = canvas.toDataURL('image/jpeg', 0.95);
  link.click();
}

export async function exportCanvasToPDF(canvas: HTMLCanvasElement, projectName = 'Floor Plan') {
  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pdfW = pdf.internal.pageSize.getWidth();
  const pdfH = pdf.internal.pageSize.getHeight();

  // Title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(projectName, 14, 15);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated by HomeDesign AI • ${new Date().toLocaleDateString()}`, 14, 22);

  // Image
  const imgWidth = pdfW - 28;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  const yPos = Math.min(28, pdfH - imgHeight - 10);

  pdf.addImage(imgData, 'PNG', 14, yPos, imgWidth, Math.min(imgHeight, pdfH - yPos - 10));

  pdf.save(`${projectName.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}

export function generateShareURL(projectId: string): string {
  return `${window.location.origin}/shared/${projectId}`;
}